export { default as TableData } from "./components/TableData/tableData.jsx";
export { default as SearchForm } from "./components/SearchForm/searchForm.jsx";
export { default as MyForm } from "./components/PopForm/form.jsx";
export { default as PopForm } from "./components/PopForm/popForm.jsx";
export { default as DraggableModal } from "./components/DraggableModal/draggableModal.jsx";
export { default as DraggablePopForm } from "./components/DraggableModal/draggablePopForm.jsx";
export { default as WangEditor } from "./components/Editor/Ueditor.jsx";
export { default as CheckTagGroup } from "./components/CheckTagGroup/checkTagGroup.jsx";
export { default as Transfer } from "./components/Transfer/Transfer.jsx"
export { default as TransferTag } from "./components/TransferTag/TransferTag.jsx";
export { default as PhotoView } from "./components/PhotoView/PhotoView.jsx";